version: '3.6'

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongo:/data/db
    ports:
      - '27017:27017'

  axonserver:
    image: axoniq/axonserver
    container_name: axonserver
    volumes:
      - ./axonserver/data:/data
      - ./axonserver/eventdata:/eventdata
      - ./axonserver/config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
